USER_SERVICE_KEY = "USER_SERVICE"
USER_CONTROLLER_KEY = "USER_CONTROLLER"
USER_REPOSITORY_KEY = "USER_REPOSITORY"
USER_HOURLY_SLOT_AVAILABILITY_REPOSITORY_KEY = "USER_HOURLY_SLOT_AVAILABILITY_REPOSITORY"


DATE_TIME_FORMAT = "%Y-%m-%d %H:%M:%S"
DATE_FORMAT = "%Y-%m-%d"


